/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Dialog.java to edit this template
 */
package poo.javaeat.interfaz;

import java.awt.HeadlessException;
import poo.javaeat.ClaseUtil;
import poo.javaeat.Comida;
import poo.javaeat.Cliente;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import poo.javaeat.Restaurante;
/**
 *
 * @author gonza
 */
public class ModRestaurante extends javax.swing.JDialog {
    private ArrayList<Comida> comidas;
    private DefaultTableModel dtm = new DefaultTableModel();
    private DefaultTableModel dtm1 = new DefaultTableModel();
    private Restaurante res;
    /**
     * Creates new form VentanaRegistroD
     */
    
    public ModRestaurante(java.awt.Dialog parent, boolean modal, Restaurante res) {
        super(parent,modal);
        initComponents();
        setLocationRelativeTo(null);
        this.res=res;
        /**Seteamos las casillas con los datos del restaurante*/
        nameText.setText (res.getNombre());
        cifText.setText (res.getCIF());
        catButton.setSelected(res.isCatering());
        gastText.setText(Double.toString(res.getGastosEnvio()));
        caliText.setText(Double.toString(res.getCalificacion()));
        enviText.setText(Integer.toString(res.getTiempoEspera()));
        calleText.setText(res.getDir().getCalle());
        numberText.setText(Integer.toString(res.getDir().getNumero()));
        cpText.setText(res.getDir().getCP());
        cityText.setText(res.getDir().getCiudad());
        switch (res.getEspecialidad()){
            case "COMIDA MEJICANA": mejiButton.setSelected(true);
            case "COMIDA ASIATICA": asiaButton.setSelected(true);
            case "COMIDA CASERA": caseButton.setSelected(true);
            case "COMIDA INDIA": indiButton.setSelected(true);
        }
        String columnas[] = {"NOMBRE", "INGREDIENTES", "PRECIO"};
        dtm.setColumnIdentifiers(columnas);
        jTable1.setModel(dtm);
        rellenaTabla(); //Tabbla con todas las comidas
        String columnas1[]={"NOMBRE", "INGREDIENTES", "PRECIO"};
        dtm1.setColumnIdentifiers(columnas1);
        jTable2.setModel(dtm1);
        rellenaTablaComSele(); //tabla con las comidas del restaurante
        this.setVisible(true);
        
    }
    
    /**Rellena la tabla con todas las comidas disponibles
     * 
     */
    public void rellenaTabla() {
        limpiaTabla();
        comidas=ClaseUtil.getComidas();
        
        ArrayList<Comida>comRes=res.getComidas();
        for (Comida com : comidas) {
            Boolean Marca=false;
            for (Comida c :comRes){
                if (com.getTitulo().equals(c.getTitulo())){
                    Marca=true;
                }
            }
            if (!Marca){dtm.addRow(new Object [] {com.getTitulo(),com.getIngredientes(),com.getPrecio()});}
        }
    }
    
    
    
    /**Rellena la tabla con las comidas dle restaurante
     * 
     */
    public void rellenaTablaComSele(){
        limpiaTabla1();
        comidas=res.getComidas();
        for (Comida com : comidas) {
            dtm1.addRow(new Object [] {com.getTitulo(),com.getIngredientes(),com.getPrecio()});
        }
    } 
    
    public void limpiaTabla() {
        int filas = dtm.getRowCount();
        for (int i = 0; i < filas; i++) {
            dtm.removeRow(0);
        }   
    }
    public void limpiaTabla1() {
        int filas = dtm1.getRowCount();
        for (int i = 0; i < filas; i++) {
            dtm1.removeRow(0);
        }   
    }
    private void getImagen() {
        try {
            labelLogo.setSize(110, 90);
            ImageIcon imagen = new ImageIcon("imagenes/JavaEatLogo.png");
            //Se redimensiona
            ImageIcon imgRedimensionada = new ImageIcon(imagen.getImage().getScaledInstance(labelLogo.getWidth(), labelLogo.getHeight(), 1));
            labelLogo.setIcon(imgRedimensionada);
        } catch (Exception e) {
            System.out.println("Error: " + e.toString());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoEspe = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        formularioLabel = new javax.swing.JLabel();
        labelLogo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        nameLabel = new javax.swing.JLabel();
        nameText = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        calleLabel = new javax.swing.JLabel();
        calleText = new javax.swing.JTextField();
        numberLabel = new javax.swing.JLabel();
        cpLabel = new javax.swing.JLabel();
        cityLabel = new javax.swing.JLabel();
        cityText = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        cifLabel = new javax.swing.JLabel();
        cifText = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        caliText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        enviText = new javax.swing.JTextField();
        catButton = new javax.swing.JToggleButton();
        jLabel3 = new javax.swing.JLabel();
        gastText = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        mejiButton = new javax.swing.JRadioButton();
        asiaButton = new javax.swing.JRadioButton();
        caseButton = new javax.swing.JRadioButton();
        indiButton = new javax.swing.JRadioButton();
        verComButton = new javax.swing.JButton();
        confirmButton = new javax.swing.JButton();
        selecButton = new javax.swing.JButton();
        verComButton1 = new javax.swing.JButton();
        elButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel7 = new javax.swing.JLabel();
        addComidaButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        cpText = new javax.swing.JFormattedTextField();
        numberText = new javax.swing.JFormattedTextField();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 102));
        jPanel2.setForeground(new java.awt.Color(255, 255, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        formularioLabel.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        formularioLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        formularioLabel.setText("CONSULTA DE RESTAURANTE");
        jPanel2.add(formularioLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 310, 40));

        getImagen();
        jPanel2.add(labelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 110, 90));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 110));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 440, -1));

        nameLabel.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        nameLabel.setText("Nombre:");
        jPanel1.add(nameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 120, -1));

        nameText.setEditable(false);
        nameText.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jPanel1.add(nameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 310, 20));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 440, 10));

        calleLabel.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        calleLabel.setText("Calle:");
        jPanel1.add(calleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 120, -1));

        calleText.setEditable(false);
        calleText.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jPanel1.add(calleText, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 310, 20));

        numberLabel.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        numberLabel.setText("Número:");
        jPanel1.add(numberLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, -1, -1));

        cpLabel.setText("Código Postal:");
        jPanel1.add(cpLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, 80, 20));

        cityLabel.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        cityLabel.setText("Ciudad:");
        jPanel1.add(cityLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, -1, 20));

        cityText.setEditable(false);
        cityText.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jPanel1.add(cityText, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 390, 380, -1));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 440, -1));

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 520, 440, -1));

        cifLabel.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        cifLabel.setText("CIF:");
        jPanel1.add(cifLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, 20));

        cifText.setEditable(false);
        cifText.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jPanel1.add(cifText, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 390, -1));

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel1.setText("Calificación:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 80, 20));

        caliText.setEditable(false);
        caliText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caliTextActionPerformed(evt);
            }
        });
        jPanel1.add(caliText, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 350, -1));

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel2.setText("Tiempo de envío:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 110, 20));

        enviText.setEditable(false);
        enviText.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jPanel1.add(enviText, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 330, 20));

        catButton.setText("Catering");
        catButton.setEnabled(false);
        jPanel1.add(catButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        jLabel3.setText("Gastos de envío:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 90, 20));

        gastText.setEditable(false);
        jPanel1.add(gastText, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, 210, 20));

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("¿Especialidad del restaurante?");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 420, 250, 30));

        grupoEspe.add(mejiButton);
        mejiButton.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        mejiButton.setText("Comida Mejicana");
        mejiButton.setEnabled(false);
        jPanel1.add(mejiButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 450, -1, -1));

        grupoEspe.add(asiaButton);
        asiaButton.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        asiaButton.setText("Comida Asiatica");
        asiaButton.setEnabled(false);
        jPanel1.add(asiaButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 480, -1, -1));

        grupoEspe.add(caseButton);
        caseButton.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        caseButton.setText("Comida Casera");
        caseButton.setEnabled(false);
        jPanel1.add(caseButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 450, -1, -1));

        grupoEspe.add(indiButton);
        indiButton.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        indiButton.setText("Comida India");
        indiButton.setEnabled(false);
        jPanel1.add(indiButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 480, -1, -1));

        verComButton.setBackground(new java.awt.Color(255, 255, 153));
        verComButton.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        verComButton.setText("VER COMIDA");
        verComButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verComButtonActionPerformed(evt);
            }
        });
        jPanel1.add(verComButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 870, 120, 20));

        confirmButton.setBackground(new java.awt.Color(255, 255, 102));
        confirmButton.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        confirmButton.setText("CONFIRMAR");
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });
        jPanel1.add(confirmButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 920, 240, 30));

        selecButton.setBackground(new java.awt.Color(255, 255, 153));
        selecButton.setText("AÑADIR COMIDA");
        selecButton.setEnabled(false);
        selecButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selecButtonActionPerformed(evt);
            }
        });
        jPanel1.add(selecButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 680, 140, -1));

        verComButton1.setBackground(new java.awt.Color(255, 255, 153));
        verComButton1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        verComButton1.setText("VER COMIDA");
        verComButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verComButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(verComButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 680, 120, 20));

        elButton.setBackground(new java.awt.Color(255, 255, 153));
        elButton.setText("ELIMINAR COMIDA");
        elButton.setEnabled(false);
        elButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elButtonActionPerformed(evt);
            }
        });
        jPanel1.add(elButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 870, 140, -1));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Comidas disponibles");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 530, 540, 20));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Comidas en la carta del restaurante");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 710, 540, 20));

        jToggleButton1.setBackground(new java.awt.Color(255, 255, 153));
        jToggleButton1.setText("MODIFICAR");
        jToggleButton1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jToggleButton1StateChanged(evt);
            }
        });
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(344, 120, 130, -1));

        jLabel7.setText("Pulse MODIFICAR para cambiar los datos ");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 230, 20));

        addComidaButton.setBackground(new java.awt.Color(255, 255, 153));
        addComidaButton.setText("CREAR COMIDA");
        addComidaButton.setEnabled(false);
        addComidaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addComidaButtonActionPerformed(evt);
            }
        });
        jPanel1.add(addComidaButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 680, 120, 20));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "NOMBRE", "INGREDIENTES", "PRECIO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jScrollPane3.setViewportView(jScrollPane1);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 550, 440, 110));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "NOMBRE", "INGREDIENTES", "PRECIO"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jScrollPane4.setViewportView(jScrollPane2);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 740, 440, 120));

        try {
            cpText.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel1.add(cpText, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 360, 140, -1));

        try {
            numberText.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel1.add(numberText, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, 120, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 539, 970));

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void caliTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caliTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caliTextActionPerformed

    /**Confirma la modificacion en el restaurante
     * 
     * @param evt 
     */
    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed
        try{
            /** Seteamos el restaurante con sus nuevos datos*/
            res.setNombre(nameText.getText());
            res.setCIF(cifText.getText());
            res.setCatering(catButton.isSelected());
            Double gastosEnvio = Double.parseDouble(gastText.getText());
            res.setGastosEnvio(gastosEnvio);
            Double calificacion = Double.parseDouble(caliText.getText());
            res.setCalificacion(calificacion);
            Integer tiempoE = Integer.parseInt(enviText.getText());
            res.setTiempoEspera(tiempoE);
            String calle = calleText.getText();
            res.getDir().setCalle(calle);
            Integer numero = Integer.parseInt(numberText.getText());
            res.getDir().setNumero(numero);
            String cp =cpText.getText();
            res.getDir().setCP(cp);
            String ciudad = cityText.getText();
            res.getDir().setCiudad(ciudad);
            if (mejiButton.isSelected()){
                String Espe = "COMIDA MEJICANA";
                res.setEspecialidad(Espe);
                }
            else if (caseButton.isSelected()){String Espe = "COMIDA CASERA";
                res.setEspecialidad(Espe);
}
            else if (asiaButton.isSelected()){String Espe = "COMIDA ASIATICA";
                res.setEspecialidad(Espe);
}
            else if (indiButton.isSelected()){String Espe = "COMIDA INDIA";
                res.setEspecialidad(Espe);
}       
            JOptionPane.showMessageDialog(this, "Restaurante Modificado", "MODIFICACION REALIZADA", JOptionPane.OK_OPTION);
            ClaseUtil.guardarDatos();
            this.dispose();
        }
        catch (HeadlessException | NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Excepción al modificar, compruebe los datos", "Mensaje", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_confirmButtonActionPerformed

    /** Introduce la comida en el restaurante si no lo esta ya
     * 
     * @param evt 
     */
    private void selecButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selecButtonActionPerformed
        // TODO add your handling code here:
        try{
            int fila = jTable1.getSelectedRow();
            int columna = 0;
            Object value = jTable1.getValueAt(fila, columna);
            String nombre= (String) value;
            ArrayList<Comida> copia= new ArrayList<>(ClaseUtil.getComidas());
            ArrayList<Comida> copia1= new ArrayList<>(res.getComidas());
            for (Comida com : copia){
                if (com.getTitulo().equals(nombre)&&(!copia1.contains(com))){
                    res.getComidas().add(com);
                    System.out.println(res.getComidas().toString());}
            }
            rellenaTabla();
            rellenaTablaComSele();
            ClaseUtil.guardarDatos();
        }
        catch(ArrayIndexOutOfBoundsException et) {
            JOptionPane.showMessageDialog(this, "Selecciona una fila ");
        }
        catch (IndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(this, "Selecciona una fila ");
        }  
    }//GEN-LAST:event_selecButtonActionPerformed

    /**Abre la ventana de ver comida
     * 
     * @param evt 
     */
    private void verComButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verComButton1ActionPerformed
        // TODO add your handling code here:
        try{
            int fila = jTable1.getSelectedRow();
        int columna = 0;
        Object value = jTable1.getValueAt(fila, columna);
        String nombre = (String) value;
        for (Comida com: ClaseUtil.getComidas()) {
            if (com.getTitulo().equals(nombre)) {
                VerComida vc = new VerComida(this, true, com);
            }
        }
            rellenaTabla();
        }
        catch(ArrayIndexOutOfBoundsException et) {
            JOptionPane.showMessageDialog(this, "Selecciona una fila ");
        }
        catch (IndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(this, "Selecciona una fila ");
        }
        
        
    }//GEN-LAST:event_verComButton1ActionPerformed

    /**nos permite modificar los datos
     * 
     * @param evt 
     */
    private void jToggleButton1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jToggleButton1StateChanged
        // TODO add your handling code here:
        if (jToggleButton1.isSelected()){
        nameText.setEditable(true);
        cifText.setEditable(true);
        catButton.setEnabled(true);
        gastText.setEditable(true);
        caliText.setEditable(true);
        enviText.setEditable(true);
        calleText.setEditable(true);
        numberText.setEditable(true);
        cpText.setEditable(true);
        cityText.setEditable(true);
        mejiButton.setEnabled(true);
        caseButton.setEnabled(true);
        asiaButton.setEnabled(true);
        indiButton.setEnabled(true);
        selecButton.setEnabled(true);
        elButton.setEnabled(true);
        addComidaButton.setEnabled(true);
        }
        else{
        nameText.setEditable(false);
        cifText.setEditable(false);
        catButton.setEnabled(false);
        gastText.setEditable(false);
        caliText.setEditable(false);
        enviText.setEditable(false);
        calleText.setEditable(false);
        numberText.setEditable(false);
        cpText.setEditable(false);
        cityText.setEditable(false);
        mejiButton.setEnabled(false);
        caseButton.setEnabled(false);
        asiaButton.setEnabled(false);
        indiButton.setEnabled(false);
        selecButton.setEnabled(false);
        elButton.setEnabled(false);
        addComidaButton.setEnabled(false);
        }
    }//GEN-LAST:event_jToggleButton1StateChanged

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton1ActionPerformed
    
    /**Elimina una comida del array del restaurante
     * 
     * @param evt 
     */
    private void elButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elButtonActionPerformed
        // TODO add your handling code here:
        try{
            int fila = jTable2.getSelectedRow();
            int columna = 0;
            Object value = jTable2.getValueAt(fila, columna);
            String nombre= (String) value;
            System.out.println("MARCADOR: "+nombre);
            ArrayList<Comida> copia= new ArrayList<>(res.getComidas());
            for (Comida com : copia){
                if (com.getTitulo().equals(nombre)){
                    if (res.getComidas().contains(com)){
                        res.moveComida(com);
                    }
                }
            }
            System.out.println(res.getComidas());
            rellenaTablaComSele();
            rellenaTabla();
        }
        catch(ArrayIndexOutOfBoundsException et) {
            JOptionPane.showMessageDialog(this, "Selecciona una fila ");
        }
        catch (IndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(this, "Selecciona una fila ");
        }
        
    }//GEN-LAST:event_elButtonActionPerformed

    /**Nos permite ver los datos de una comida
     * 
     * @param evt 
     */
    private void verComButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verComButtonActionPerformed
        // TODO add your handling code here:
        try{
        int fila = jTable2.getSelectedRow();
        Comida com = res.getComidas().get(fila);
        VerComida v =new VerComida (this, true,com);
        rellenaTablaComSele();
        }
        catch(ArrayIndexOutOfBoundsException et) {
            JOptionPane.showMessageDialog(this, "Selecciona una fila ");
        }
        catch (IndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(this, "Selecciona una fila ");
        }
    }//GEN-LAST:event_verComButtonActionPerformed

    private void addComidaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addComidaButtonActionPerformed
        // TODO add your handling code here:
        AltaComida v =new AltaComida (this,true);
        rellenaTabla();
    }//GEN-LAST:event_addComidaButtonActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addComidaButton;
    private javax.swing.JRadioButton asiaButton;
    private javax.swing.JTextField caliText;
    private javax.swing.JLabel calleLabel;
    private javax.swing.JTextField calleText;
    private javax.swing.JRadioButton caseButton;
    private javax.swing.JToggleButton catButton;
    private javax.swing.JLabel cifLabel;
    private javax.swing.JTextField cifText;
    private javax.swing.JLabel cityLabel;
    private javax.swing.JTextField cityText;
    private javax.swing.JButton confirmButton;
    private javax.swing.JLabel cpLabel;
    private javax.swing.JFormattedTextField cpText;
    private javax.swing.JButton elButton;
    private javax.swing.JTextField enviText;
    private javax.swing.JLabel formularioLabel;
    private javax.swing.JTextField gastText;
    private javax.swing.ButtonGroup grupoEspe;
    private javax.swing.JRadioButton indiButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel labelLogo;
    private javax.swing.JRadioButton mejiButton;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameText;
    private javax.swing.JLabel numberLabel;
    private javax.swing.JFormattedTextField numberText;
    private javax.swing.JButton selecButton;
    private javax.swing.JButton verComButton;
    private javax.swing.JButton verComButton1;
    // End of variables declaration//GEN-END:variables
}
