/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Dialog.java to edit this template
 */
package poo.javaeat.interfaz;

import java.awt.HeadlessException;
import poo.javaeat.ClaseUtil;
import poo.javaeat.Comida;
import poo.javaeat.Cliente;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import poo.javaeat.Direccion;
import poo.javaeat.Restaurante;
/**
 *
 * @author gonza
 */
public class VAltaRestaurante extends javax.swing.JDialog {
    private ArrayList<Comida> comSelecc;
    private ArrayList<Comida> comidas;
    private DefaultTableModel dtm = new DefaultTableModel();
    private DefaultTableModel dtm1 = new DefaultTableModel();
    /**
     * Creates new form VentanaRegistroD
     */
    
    public VAltaRestaurante(java.awt.Dialog parent, boolean modal) {
        super(parent,modal);
        setLocationRelativeTo(null);
        initComponents();
        comSelecc = new ArrayList<>();
        String columnas[] = {"NOMBRE", "INGREDIENTES", "PRECIO"};
        dtm.setColumnIdentifiers(columnas);
        comTable.setModel(dtm);
        rellenaTabla();
        String columnas1[]={"NOMBRE", "INGREDIENTES", "PRECIO"};
        dtm1.setColumnIdentifiers(columnas1);
        jTable1.setModel(dtm1);
        this.setVisible(true);
        
    }
    /**Rellena la tabla con todas las comidas disponibles
     * 
     */
    public void rellenaTabla() {
        limpiaTabla();
        comidas=ClaseUtil.getComidas();
        for (Comida com : comidas) {
            Boolean Marca=false; // para saber si la comida esta dentro del restaurante y por tanto no la metenmos en la tabla
            for (Comida c :comSelecc){
                if (com.getTitulo().equals(c.getTitulo())){
                    Marca=true;
                }
            }
            if (!Marca){dtm.addRow(new Object [] {com.getTitulo(),com.getIngredientes(),com.getPrecio()});}
        }
    }
    
    /**Rellena la tabla con todas las comidas del restaurante
     * 
     */
    public void rellenaTablaComSele(){
        limpiaTabla1();
        comidas=comSelecc;
        for (Comida com : comidas) {
            dtm1.addRow(new Object [] {com.getTitulo(),com.getIngredientes(),com.getPrecio()});
        }
    } 
    
    
    public void limpiaTabla() {
        int filas = dtm.getRowCount();
        for (int i = 0; i < filas; i++) {
            dtm.removeRow(0);
        }   
    }
    public void limpiaTabla1() {
        int filas = dtm1.getRowCount();
        for (int i = 0; i < filas; i++) {
            dtm1.removeRow(0);
        }   
    }
    private void getImagen() {
        try {
            labelLogo.setSize(120, 90);
            ImageIcon imagen = new ImageIcon("imagenes/JavaEatLogo.png");
            //Se redimensiona
            ImageIcon imgRedimensionada = new ImageIcon(imagen.getImage().getScaledInstance(labelLogo.getWidth(), labelLogo.getHeight(), 1));
            labelLogo.setIcon(imgRedimensionada);
        } catch (Exception e) {
            System.out.println("Error: " + e.toString());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoEspe = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        formularioLabel = new javax.swing.JLabel();
        labelLogo = new javax.swing.JLabel();
        correoLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        nameLabel = new javax.swing.JLabel();
        nameText = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        calleLabel = new javax.swing.JLabel();
        calleText = new javax.swing.JTextField();
        numberLabel = new javax.swing.JLabel();
        cpLabel = new javax.swing.JLabel();
        cityLabel = new javax.swing.JLabel();
        cityText = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        cifLabel = new javax.swing.JLabel();
        cifText = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        caliText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        enviText = new javax.swing.JTextField();
        catButton = new javax.swing.JToggleButton();
        jLabel3 = new javax.swing.JLabel();
        gastText = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        mejiButton = new javax.swing.JRadioButton();
        asiaButton = new javax.swing.JRadioButton();
        caseButton = new javax.swing.JRadioButton();
        indiButton = new javax.swing.JRadioButton();
        altaButton = new javax.swing.JButton();
        verComButton = new javax.swing.JButton();
        addComidaButton = new javax.swing.JButton();
        selecButton = new javax.swing.JButton();
        elButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        comTable = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        cpText = new javax.swing.JFormattedTextField();
        numberText = new javax.swing.JFormattedTextField();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 102));
        jPanel2.setForeground(new java.awt.Color(255, 255, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        formularioLabel.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        formularioLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        formularioLabel.setText("REGISTRO DE RESTAURANTE");
        jPanel2.add(formularioLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, 280, 40));

        getImagen();
        jPanel2.add(labelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 120, 90));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 110));

        correoLabel.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jPanel1.add(correoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 130, 20));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 440, -1));

        nameLabel.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        nameLabel.setText("Nombre:");
        jPanel1.add(nameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 120, -1));

        nameText.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jPanel1.add(nameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 310, -1));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 440, 10));

        calleLabel.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        calleLabel.setText("Calle:");
        jPanel1.add(calleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 120, -1));

        calleText.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jPanel1.add(calleText, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, 310, 20));

        numberLabel.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        numberLabel.setText("Número:");
        jPanel1.add(numberLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, -1, -1));

        cpLabel.setText("Código Postal:");
        jPanel1.add(cpLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 340, 80, 20));

        cityLabel.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        cityLabel.setText("Ciudad:");
        jPanel1.add(cityLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, -1, 20));

        cityText.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jPanel1.add(cityText, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, 380, -1));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 440, -1));

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 490, 440, -1));

        cifLabel.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        cifLabel.setText("CIF:");
        jPanel1.add(cifLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, 20));

        cifText.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jPanel1.add(cifText, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 390, -1));

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel1.setText("Calificación:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 80, 20));

        caliText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caliTextActionPerformed(evt);
            }
        });
        jPanel1.add(caliText, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 350, -1));

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel2.setText("Tiempo de envío:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 110, 20));

        enviText.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jPanel1.add(enviText, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 330, 20));

        catButton.setText("Catering");
        jPanel1.add(catButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        jLabel3.setText("Gastos de envío:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 90, 20));
        jPanel1.add(gastText, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 210, 20));

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("¿Especialidad del restaurante?");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 400, 250, 30));

        grupoEspe.add(mejiButton);
        mejiButton.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        mejiButton.setText("Comida Mejicana");
        jPanel1.add(mejiButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 430, -1, -1));

        grupoEspe.add(asiaButton);
        asiaButton.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        asiaButton.setText("Comida Asiatica");
        jPanel1.add(asiaButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 460, -1, -1));

        grupoEspe.add(caseButton);
        caseButton.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        caseButton.setText("Comida Casera");
        jPanel1.add(caseButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 430, -1, -1));

        grupoEspe.add(indiButton);
        indiButton.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        indiButton.setText("Comida India");
        jPanel1.add(indiButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 460, -1, -1));

        altaButton.setBackground(new java.awt.Color(255, 255, 102));
        altaButton.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        altaButton.setText("ALTA");
        altaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                altaButtonActionPerformed(evt);
            }
        });
        jPanel1.add(altaButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 830, 240, 30));

        verComButton.setBackground(new java.awt.Color(255, 255, 153));
        verComButton.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        verComButton.setText("VER COMIDA");
        verComButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verComButtonActionPerformed(evt);
            }
        });
        jPanel1.add(verComButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 620, 120, 20));

        addComidaButton.setBackground(new java.awt.Color(255, 255, 153));
        addComidaButton.setText("CREAR COMIDA");
        addComidaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addComidaButtonActionPerformed(evt);
            }
        });
        jPanel1.add(addComidaButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 620, 120, 20));

        selecButton.setBackground(new java.awt.Color(255, 255, 153));
        selecButton.setText("ADD COMIDA");
        selecButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selecButtonActionPerformed(evt);
            }
        });
        jPanel1.add(selecButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 620, 140, -1));

        elButton.setBackground(new java.awt.Color(255, 255, 153));
        elButton.setText("ELIMINAR COMIDA");
        elButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elButtonActionPerformed(evt);
            }
        });
        jPanel1.add(elButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 790, 140, -1));

        comTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "NOMBRE", "INGREDIENTES", "PRECIO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(comTable);

        jScrollPane3.setViewportView(jScrollPane1);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 500, 440, 110));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "NOMBRE", "INGREDIENTES", "PRECIO"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jScrollPane4.setViewportView(jScrollPane2);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 660, 440, 110));

        try {
            cpText.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel1.add(cpText, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 340, 140, -1));

        try {
            numberText.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel1.add(numberText, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, 120, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 539, 880));

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void caliTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caliTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caliTextActionPerformed

    /**Das de alta un restaurante 
     * 
     * @param evt 
     */
    private void altaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_altaButtonActionPerformed
        try{
            String nombre =nameText.getText();
            String cif = cifText.getText();
            Boolean catering = catButton.isSelected();
            Double gastosEnvio = Double.parseDouble(gastText.getText());
            Double calificacion = Double.parseDouble(caliText.getText());
            Integer tiempoE = Integer.parseInt(enviText.getText());
            String calle = calleText.getText();
            Integer numero = Integer.parseInt(numberText.getText());
            String cp =cpText.getText();
            String ciudad = cityText.getText();
            String Espe="NINGUNO";
            Direccion d = new Direccion (calle, numero, cp, ciudad);
            if (mejiButton.isSelected()){ Espe = "COMIDA MEJICANA";}
            else if (caseButton.isSelected()){Espe = "COMIDA CASERA";}
            else if (asiaButton.isSelected()){Espe = "COMIDA ASIATICA";}
            else if (indiButton.isSelected()){Espe = "COMIDA INDIA";}
            Restaurante res = new Restaurante (nombre,cif,d,Espe,gastosEnvio,tiempoE,catering,comSelecc);
            ClaseUtil.altaRestaurante(res);
            ClaseUtil.guardarDatos();
            this.dispose();
        }
        catch (HeadlessException | NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Excepción al guardar cambios, compruebe los datos", "Mensaje", JOptionPane.ERROR_MESSAGE);}
    }//GEN-LAST:event_altaButtonActionPerformed

    /**Te permite crear una comida
     * 
     * @param evt 
     */
    private void addComidaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addComidaButtonActionPerformed
        // TODO add your handling code here:
        AltaComida v =new AltaComida (this,true);
        rellenaTabla();
    }//GEN-LAST:event_addComidaButtonActionPerformed

    /**Permite meter una comida al array del restaurante
     * 
     * @param evt 
     */
    private void selecButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selecButtonActionPerformed
        // TODO add your handling code here:
        try{
            int fila = comTable.getSelectedRow();
            int columna = 0;
            Object value = comTable.getValueAt(fila, columna);
            String nombre= (String) value;
            ArrayList<Comida> copia= new ArrayList<>(ClaseUtil.getComidas());
            for (Comida com : copia){
                if (com.getTitulo().equals(nombre)&&(!comSelecc.contains(com))){
                    comSelecc.add(com);
                    rellenaTabla();
                    rellenaTablaComSele();
                    System.out.println(comSelecc.toString());}
            }
            ClaseUtil.guardarDatos();
        }
        catch(ArrayIndexOutOfBoundsException et) {
            JOptionPane.showMessageDialog(this, "Selecciona una fila ");
        }
        catch (IndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(this, "Selecciona una fila ");
        }
    }//GEN-LAST:event_selecButtonActionPerformed

    /**Te permite ver los datos de una comida
     * 
     * @param evt 
     */
    private void verComButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verComButtonActionPerformed
        // TODO add your handling code here:
        int fila = comTable.getSelectedRow();
        int columna = 0;
        Object value = comTable.getValueAt(fila, columna);
        String nombre = (String) value;
        for (Comida com: ClaseUtil.getComidas()) {
            if (com.getTitulo().equals(nombre)) {
                VerComida vc = new VerComida(this, true, com);
                rellenaTabla();
            }
        }
    }//GEN-LAST:event_verComButtonActionPerformed

    /**Te permite eliminar una comida del restaurante 
     * 
     * @param evt 
     */
    private void elButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elButtonActionPerformed
        // TODO add your handling code here:
        int fila = jTable1.getSelectedRow();
        int columna = 0;
        Object value = jTable1.getValueAt(fila, columna);
        String nombre= (String) value;
        System.out.println("MARCADOR: "+nombre);
        ArrayList<Comida> copia= new ArrayList<>(comSelecc);
        for (Comida com : copia){
            if (com.getTitulo().equals(nombre)){
                if (comSelecc.contains(com)){
                    comSelecc.remove(com);
                }
                else {
                    JOptionPane.showMessageDialog(this, "La Comida no esta en la carta y no se ha podido eliminar", "Error al eliminarq", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
        rellenaTablaComSele();
        rellenaTabla();
    }//GEN-LAST:event_elButtonActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addComidaButton;
    private javax.swing.JButton altaButton;
    private javax.swing.JRadioButton asiaButton;
    private javax.swing.JTextField caliText;
    private javax.swing.JLabel calleLabel;
    private javax.swing.JTextField calleText;
    private javax.swing.JRadioButton caseButton;
    private javax.swing.JToggleButton catButton;
    private javax.swing.JLabel cifLabel;
    private javax.swing.JTextField cifText;
    private javax.swing.JLabel cityLabel;
    private javax.swing.JTextField cityText;
    private javax.swing.JTable comTable;
    private javax.swing.JLabel correoLabel;
    private javax.swing.JLabel cpLabel;
    private javax.swing.JFormattedTextField cpText;
    private javax.swing.JButton elButton;
    private javax.swing.JTextField enviText;
    private javax.swing.JLabel formularioLabel;
    private javax.swing.JTextField gastText;
    private javax.swing.ButtonGroup grupoEspe;
    private javax.swing.JRadioButton indiButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labelLogo;
    private javax.swing.JRadioButton mejiButton;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameText;
    private javax.swing.JLabel numberLabel;
    private javax.swing.JFormattedTextField numberText;
    private javax.swing.JButton selecButton;
    private javax.swing.JButton verComButton;
    // End of variables declaration//GEN-END:variables
}
