/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package poo.javaeat.interfaz;

import java.util.ArrayList;
import java.util.Collections;
import java.util.ListIterator;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import poo.javaeat.ClaseUtil;
import poo.javaeat.Cliente;
import poo.javaeat.Restaurante;

/**
 *
 * @author gonza
 */
public class vcBusquedaRestaurantes extends javax.swing.JDialog {
    private ArrayList<Restaurante> restaurantes = new ArrayList<>();
    private DefaultTableModel dtm = new DefaultTableModel();
    private Cliente cliente;
    /**
     * Creates new form ConsultaRestaurantes
     */
    public vcBusquedaRestaurantes(java.awt.Dialog parent, boolean modal, Cliente cliente) {
        super(parent, modal);
        initComponents();
        this.cliente=cliente;
        this.setLocationRelativeTo(null);
        String columnas[] = {"NOMBRE", "CALIFICACION", "CATERING", "ESPECIALIDAD","TIEMPO DE ESPERA"};
        dtm.setColumnIdentifiers(columnas);
        tablaRestaurantes.setModel(dtm);
        //verRestauranteButton.setEnabled(true);
        rellenaTabla(ClaseUtil.getRestaurantes());
        this.setVisible(true);
    }
    
    public void rellenaTabla(ArrayList<Restaurante> r) {
        limpiaTabla();
        System.out.println(r);
        for (Restaurante res : r) {
            dtm.addRow(new Object [] {res.getNombre(),res.getCalificacion(),res.isCatering(),res.getEspecialidad(),res.getTiempoEspera()});
        }
    }
    public void limpiaTabla() {
        int filas = dtm.getRowCount();
        for (int i = 0; i < filas; i++) {
            dtm.removeRow(0);
        }   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void getImagen() {
        try {
            labelLogo.setSize(143, 138);
            ImageIcon imagen = new ImageIcon("imagenes/JavaEatLogo.png");
            //Se redimensiona
            ImageIcon imgRedimensionada = new ImageIcon(imagen.getImage().getScaledInstance(labelLogo.getWidth(), labelLogo.getHeight(), 1));
            labelLogo.setIcon(imgRedimensionada);
        } catch (Exception e) {
            System.out.println("Error: " + e.toString());
        }
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        labelLogo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        filtroOrden = new javax.swing.JComboBox<>();
        filtroEspe = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        verRestauranteButton = new javax.swing.JButton();
        volveButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaRestaurantes = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 102));

        getImagen();

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel1.setText("CONSULTA DE RESTAURANTES");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(labelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        filtroOrden.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NINGUNO", "CALIFICACION", "TIEMPO DE ESPERA", "CATERING", "CERCANIA", " " }));
        filtroOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtroOrdenActionPerformed(evt);
            }
        });

        filtroEspe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NINGUNO", "COMIDA ASIÁTICA", "COMIDA MEJICANA", "COMIDA CASERA", "COMIDA INDIA" }));
        filtroEspe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtroEspeActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel2.setText("Ordenar por:");

        jLabel3.setText("Especialidad:");

        verRestauranteButton.setBackground(new java.awt.Color(255, 255, 102));
        verRestauranteButton.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        verRestauranteButton.setText("SELECCIONAR");
        verRestauranteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verRestauranteButtonActionPerformed(evt);
            }
        });

        volveButton.setText("Volver");
        volveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volveButtonActionPerformed(evt);
            }
        });

        tablaRestaurantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "NOMBRE", "CALIFICACION", "CATERING", "ESPECIALIDAD", "TIEMPO_ESPERA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaRestaurantes);

        jScrollPane2.setViewportView(jScrollPane1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(volveButton)
                        .addGap(74, 74, 74)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(filtroOrden, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(149, 149, 149)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(filtroEspe, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addComponent(verRestauranteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(volveButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(filtroEspe, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(filtroOrden))
                        .addGap(37, 37, 37)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(verRestauranteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**Muestra la tabla ordenada segun los valores de los JComboBox
     * 
     * @param evt 
     */
    private void filtroOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filtroOrdenActionPerformed
        if (((String)filtroOrden.getSelectedItem()).equals("NINGUNO")&&((String)filtroEspe.getSelectedItem()).equals("NINGUNO")){
            rellenaTabla(ClaseUtil.getRestaurantes());}
        else if (((String)filtroOrden.getSelectedItem()).equals("CALIFICACION")&& ((String)filtroEspe.getSelectedItem()).equals("NINGUNO")){
            ArrayList<Restaurante>res =ClaseUtil.ordenarRelevancia();
            Collections.reverse(res);
            rellenaTabla(res);
        }                   
        else if (((String)filtroOrden.getSelectedItem()).equals("TIEMPO DE ESPERA")&&((String)filtroEspe.getSelectedItem()).equals("NINGUNO")){  
            rellenaTabla(ClaseUtil.ordenarTMedio());
        }
        else if (((String)filtroOrden.getSelectedItem()).equals("CATERING")&&((String)filtroEspe.getSelectedItem()).equals("NINGUNO")){
            rellenaTabla(ClaseUtil.ordenarCatering());
            }  
        else if (((String)filtroOrden.getSelectedItem()).equals("CERCANIA")&&((String)filtroEspe.getSelectedItem()).equals("NINGUNO")){
            rellenaTabla (ClaseUtil.ordenarCercania(cliente));
        }
        else if (((String)filtroOrden.getSelectedItem()).equals("CALIFICACION")&& !((String)filtroEspe.getSelectedItem()).equals("NINGUNO")){
            ArrayList<Restaurante>res =ClaseUtil.ordenarRelevancia();
            Collections.reverse(res);
            rellenaTabla(ClaseUtil.filtroEspecialidad(res, (String)filtroEspe.getSelectedItem()));
        }
        else if (((String)filtroOrden.getSelectedItem()).equals("TIEMPO DE ESPERA")&& !((String)filtroEspe.getSelectedItem()).equals("NINGUNO")){
            rellenaTabla(ClaseUtil.filtroEspecialidad(ClaseUtil.ordenarTMedio(), (String)filtroEspe.getSelectedItem()));
        }
        else if (((String)filtroOrden.getSelectedItem()).equals("CATERING")&& !((String)filtroEspe.getSelectedItem()).equals("NINGUNO")){
            rellenaTabla(ClaseUtil.filtroEspecialidad(ClaseUtil.ordenarCatering(), (String)filtroEspe.getSelectedItem()));
        }
        else if (((String)filtroOrden.getSelectedItem()).equals("CERCANIA")&& !((String)filtroEspe.getSelectedItem()).equals("NINGUNO")){
            rellenaTabla(ClaseUtil.filtroEspecialidad(ClaseUtil.ordenarCercania(cliente), (String)filtroEspe.getSelectedItem()));
        }
    }//GEN-LAST:event_filtroOrdenActionPerformed

    private void volveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volveButtonActionPerformed
        //poner vetnana de advertenciayes no cancel option
        dispose();
    }//GEN-LAST:event_volveButtonActionPerformed

    /**Se les muestra la ventana para pedir la comida
     * 
     * @param evt 
     */
    private void verRestauranteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verRestauranteButtonActionPerformed
        try{
            int fila = tablaRestaurantes.getSelectedRow();
        vcPedirRestaurante pR = new vcPedirRestaurante(this, true, ClaseUtil.getRestaurantes().get(fila));
        rellenaTabla(ClaseUtil.getRestaurantes());
        }
        catch(ArrayIndexOutOfBoundsException et) {
            JOptionPane.showMessageDialog(this, "Selecciona una fila ");
        }
        catch (IndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(this, "Selecciona una fila ");
        }
    }//GEN-LAST:event_verRestauranteButtonActionPerformed

    /**Se muestar la informacion ordenada segun especialidad
     * 
     * @param evt 
     */
    private void filtroEspeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filtroEspeActionPerformed
        // TODO add your handling code here:
        if (!((String)filtroEspe.getSelectedItem()).equals("NINGUNO")){
        rellenaTabla(ClaseUtil.filtroEspecialidad(ClaseUtil.getRestaurantes(), (String)filtroEspe.getSelectedItem()));}
        else{
            rellenaTabla(ClaseUtil.getRestaurantes());
        }
    }//GEN-LAST:event_filtroEspeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> filtroEspe;
    private javax.swing.JComboBox<String> filtroOrden;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelLogo;
    private javax.swing.JTable tablaRestaurantes;
    private javax.swing.JButton verRestauranteButton;
    private javax.swing.JButton volveButton;
    // End of variables declaration//GEN-END:variables
}
