/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Dialog.java to edit this template
 */
package poo.javaeat.interfaz;

import java.awt.HeadlessException;
import java.time.Instant;
import javax.swing.JOptionPane;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import javax.swing.ImageIcon;
import poo.javaeat.Direccion;
import poo.javaeat.Tarjeta;
import poo.javaeat.Empresa;
import poo.javaeat.Particular;
import poo.javaeat.ClaseUtil;
import poo.javaeat.CestaEmpresa;
import poo.javaeat.CestaParticular;
import poo.javaeat.Cliente;
/**
 *
 * @author gonza
 */
public class vcVerUsu extends javax.swing.JDialog {
    
    /**
     * Creates new form VentanaRegistroD
     */
    
    //Atributos 
    private Cliente cliente; //cada vez que se abre una ventana, esta tiene un atributo que es el cliente (referencia al cliente que la abre o del que se trata
    
    //Constructores
    public vcVerUsu(java.awt.Dialog parent, boolean modal, Empresa empresa) {
        super(parent,modal);
        setLocationRelativeTo(null);
        initComponents();
        //this.setLocationRelativeTo(null);
        this.cliente = empresa;
        
        //Activamos las casillas de empresa (cif, web)
        cifText.setEnabled(true);
        webText.setEnabled(true);
        correoText.setEditable(false); //El correo no se puede cambiar
        
        //Seteamos texto de casilas
        tipoUsuText.setText("Empresa");
        cifText.setText(empresa.getCIF());
        webText.setText(empresa.getWeb());
        correoText.setText(empresa.getCorreo());
        passText.setText(empresa.getClave());
        nameText.setText(empresa.getNombre());
        teleText.setText(empresa.getTelf());
        calleText.setText(empresa.getDireccion().getCalle());
        numberText.setText( Integer.toString(empresa.getDireccion().getNumero()));
        cpText.setText(empresa.getDireccion().getCP());
        cityText.setText(empresa.getDireccion().getCiudad());
        numTarText.setText(empresa.getTarjeta().getNumero());
        titularText.setText(empresa.getTarjeta().getTitular());
        fechaCadText.setText(empresa.getTarjeta().getFechaCad().toString());
        jSpinner1.setVisible(false);
        this.setVisible(true);
    }
    
    public vcVerUsu(java.awt.Dialog parent, boolean modal, Particular particular){
        super (parent,modal);
        setLocationRelativeTo(null);
        initComponents();
        this.cliente = particular;
        
        //Activamos las casillas de particular
        dniText.setEnabled(true);
        correoText.setEditable(false); //El correo no se puede modificar
        
        //Seteamos texto de casillas
        tipoUsuText.setText("Particular");
        dniText.setText(particular.getDNI());
        correoText.setText(particular.getCorreo());
        passText.setText(particular.getClave());
        nameText.setText(particular.getNombre());
        teleText.setText(particular.getTelf());
        calleText.setText(particular.getDireccion().getCalle());
        numberText.setText( Integer.toString(particular.getDireccion().getNumero()));
        cpText.setText(particular.getDireccion().getCP());
        cityText.setText(particular.getDireccion().getCiudad());
        numTarText.setText(particular.getTarjeta().getNumero());
        titularText.setText(particular.getTarjeta().getTitular());
        fechaCadText.setText(particular.getTarjeta().getFechaCad().toString());
        jSpinner1.setVisible(false);
        this.setVisible(true);
        
    }
    private void getImagen() {
        try {
            labelLogo.setSize(150, 110);
            ImageIcon imagen = new ImageIcon("imagenes/JavaEatLogo.png");
            //Se redimensiona
            ImageIcon imgRedimensionada = new ImageIcon(imagen.getImage().getScaledInstance(labelLogo.getWidth(), labelLogo.getHeight(), 1));
            labelLogo.setIcon(imgRedimensionada);
        } catch (Exception e) {
            System.out.println("Error: " + e.toString());
        }
    }
    //Actions
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoCliente = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        formularioLabel = new javax.swing.JLabel();
        labelLogo = new javax.swing.JLabel();
        correoLabel = new javax.swing.JLabel();
        correoText = new javax.swing.JTextField();
        passLabel = new javax.swing.JLabel();
        passText = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        nameLabel = new javax.swing.JLabel();
        teleLabel = new javax.swing.JLabel();
        nameText = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        calleLabel = new javax.swing.JLabel();
        calleText = new javax.swing.JTextField();
        numberLabel = new javax.swing.JLabel();
        cpLabel = new javax.swing.JLabel();
        cityLabel = new javax.swing.JLabel();
        cityText = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        numTarLabel = new javax.swing.JLabel();
        titularLabel = new javax.swing.JLabel();
        titularText = new javax.swing.JTextField();
        fechaCadLabel = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        dniLabel = new javax.swing.JLabel();
        dniText = new javax.swing.JTextField();
        webLabel = new javax.swing.JLabel();
        webText = new javax.swing.JTextField();
        cifLabel = new javax.swing.JLabel();
        cifText = new javax.swing.JTextField();
        tipoUsuLabel = new javax.swing.JLabel();
        tipoUsuText = new javax.swing.JTextField();
        fechaCadText = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        teleText = new javax.swing.JFormattedTextField();
        cpText = new javax.swing.JFormattedTextField();
        numTarText = new javax.swing.JFormattedTextField();
        jSpinner1 = new javax.swing.JSpinner();
        numberText = new javax.swing.JFormattedTextField();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 102));
        jPanel2.setForeground(new java.awt.Color(255, 255, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        formularioLabel.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        formularioLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        formularioLabel.setText("CONSULTA DE USUARIO");
        jPanel2.add(formularioLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 280, 40));

        getImagen();
        jPanel2.add(labelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 110));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 110));

        correoLabel.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        correoLabel.setText("Correo electrónico:");
        jPanel1.add(correoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 130, 20));

        correoText.setEditable(false);
        correoText.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        correoText.setText("ingrese su correo electronico");
        correoText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                correoTextMouseClicked(evt);
            }
        });
        jPanel1.add(correoText, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 135, 310, 30));
        correoText.getAccessibleContext().setAccessibleName("");

        passLabel.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        passLabel.setText("Contraseña:");
        jPanel1.add(passLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 120, -1));

        passText.setEditable(false);
        passText.setText("jPasswordField1");
        jPanel1.add(passText, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 310, -1));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 440, -1));

        nameLabel.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        nameLabel.setText("Nombre:");
        jPanel1.add(nameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 120, -1));

        teleLabel.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        teleLabel.setText("Teléfono:");
        jPanel1.add(teleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 120, -1));

        nameText.setEditable(false);
        nameText.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        nameText.setText("ingrese su nombre");
        jPanel1.add(nameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 310, -1));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 440, 10));

        calleLabel.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        calleLabel.setText("Calle:");
        jPanel1.add(calleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 120, -1));

        calleText.setEditable(false);
        calleText.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        calleText.setText("ingrese su calle");
        calleText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calleTextActionPerformed(evt);
            }
        });
        jPanel1.add(calleText, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 310, 30));

        numberLabel.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        numberLabel.setText("Número:");
        jPanel1.add(numberLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, -1));

        cpLabel.setText("Código Postal:");
        jPanel1.add(cpLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, 80, 20));

        cityLabel.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        cityLabel.setText("Ciudad:");
        jPanel1.add(cityLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, -1, 20));

        cityText.setEditable(false);
        cityText.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        cityText.setText("ingrese su ciudad");
        jPanel1.add(cityText, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, 380, -1));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 440, -1));

        numTarLabel.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        numTarLabel.setText("Número de tarjeta:");
        jPanel1.add(numTarLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, -1, 20));

        titularLabel.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        titularLabel.setText("Titular:");
        titularLabel.setToolTipText("");
        jPanel1.add(titularLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, -1, 20));

        titularText.setEditable(false);
        titularText.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        titularText.setText("ingrese el titular de la tarjeta");
        jPanel1.add(titularText, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 410, 390, -1));

        fechaCadLabel.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        fechaCadLabel.setText("Fecha de caducidad:");
        jPanel1.add(fechaCadLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, -1, 20));

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, 440, -1));

        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 550, 440, -1));

        dniLabel.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        dniLabel.setText("DNI:");
        jPanel1.add(dniLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 560, 40, 20));

        dniText.setEditable(false);
        dniText.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        dniText.setText("ingrese su DNI");
        dniText.setEnabled(false);
        jPanel1.add(dniText, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 560, 390, -1));

        webLabel.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        webLabel.setText("Web:");
        jPanel1.add(webLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 620, -1, 20));

        webText.setEditable(false);
        webText.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        webText.setText("ingrese la web de su empresa");
        webText.setEnabled(false);
        jPanel1.add(webText, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 620, 390, -1));

        cifLabel.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        cifLabel.setText("CIF:");
        jPanel1.add(cifLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 590, -1, 20));

        cifText.setEditable(false);
        cifText.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        cifText.setText("ingrese el CIF de su empresa");
        cifText.setEnabled(false);
        jPanel1.add(cifText, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 590, 390, -1));

        tipoUsuLabel.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        tipoUsuLabel.setText("Tipo de usuario:");
        jPanel1.add(tipoUsuLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 490, 100, 40));

        tipoUsuText.setEditable(false);
        tipoUsuText.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jPanel1.add(tipoUsuText, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 492, 290, 40));

        fechaCadText.setEditable(false);
        fechaCadText.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jPanel1.add(fechaCadText, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 440, 130, -1));

        jButton1.setBackground(new java.awt.Color(255, 255, 102));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setText("CANCELAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 710, 140, 40));

        jButton2.setBackground(new java.awt.Color(255, 255, 102));
        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton2.setText("MODIFICAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 710, 140, 40));

        jButton3.setBackground(new java.awt.Color(255, 255, 102));
        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton3.setText("GUARDAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 710, 140, 40));

        jButton4.setText("Volver");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, 20));

        try {
            teleText.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("### ## ## ##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel1.add(teleText, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 310, -1));

        try {
            cpText.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel1.add(cpText, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 310, 140, -1));

        try {
            numTarText.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-####-####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel1.add(numTarText, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, 320, 30));

        jSpinner1.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(1717093740000L), new java.util.Date(), null, java.util.Calendar.DAY_OF_WEEK_IN_MONTH));
        jPanel1.add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 440, 150, -1));

        try {
            numberText.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel1.add(numberText, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, 120, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 539, 820));

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void correoTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_correoTextMouseClicked
        correoText.setText("");
    }//GEN-LAST:event_correoTextMouseClicked

    private void calleTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calleTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_calleTextActionPerformed
//botón modificar
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        if (tipoUsuText.getText().equals("Empresa")) {
            webText.setEditable(true); //CIF no se puede cambiar y en particularea DNI tampoco    
        }
        passText.setEditable(true);
        nameText.setEditable(true);
        teleText.setEditable(true);
        calleText.setEditable(true);
        numberText.setEditable(true);
        cpText.setEditable(true);
        cityText.setEditable(true); 
        numTarText.setEditable(true);
        titularText.setEditable(true);
        jSpinner1.setVisible(true); //Ponemos visible un jSpinner para seleccionar la fecha, y la casilla de fecha solo sirve para mostrar la fechaCad actual
    }//GEN-LAST:event_jButton2ActionPerformed
//boton cancel
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        if (tipoUsuText.getText().equals("Empresa")) {
            Empresa empresa = (Empresa) cliente;
            webText.setText(empresa.getWeb()); //ponemos lo que había antes
            webText.setEditable(false);
        }
        //Seteamos de nuevo los valores anteriores
        passText.setText(cliente.getClave());
        nameText.setText(cliente.getNombre());
        teleText.setText(cliente.getTelf());
        calleText.setText(cliente.getDireccion().getCalle());
        numberText.setText(Integer.toString(cliente.getDireccion().getNumero()));
        cpText.setText(cliente.getDireccion().getCP());
        cityText.setText(cliente.getDireccion().getCiudad());  
        numTarText.setText(cliente.getTarjeta().getNumero());
        titularText.setText(cliente.getTarjeta().getTitular());

        jSpinner1.setVisible(false); //Ocultamos jSpinner
        
        //Ya no son editables los campos
        passText.setEditable(false);
        nameText.setEditable(false);
        teleText.setEditable(false);
        calleText.setEditable(false);
        numberText.setEditable(false);
        cpText.setEditable(false);
        cityText.setEditable(false); 
        numTarText.setEditable(false);
        titularText.setEditable(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    
//botón guardar cambios
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (cliente.getClass().getSimpleName().equals("Empresa")) {
            Empresa empresa = (Empresa) cliente;
            empresa.setWeb(webText.getText());
            webText.setText(empresa.getWeb());
            webText.setEditable(false);
           System.out.println("Se ejecuta");
            
        }
        try{
            //Seteamos los gatos al usuario
            cliente.setClave(passText.getText());
            cliente.setNombre(nameText.getText());
            cliente.setTelf(teleText.getText());
            cliente.getDireccion().setCalle(calleText.getText());
            
            cliente.getDireccion().setNumero(Integer.parseInt(numberText.getText()));
            cliente.getDireccion().setCP(cpText.getText());
            cliente.getDireccion().setCiudad(cityText.getText());
            cliente.getTarjeta().setNumero(numTarText.getText());
            cliente.getTarjeta().setTitular(titularText.getText());
            
            Date fecha = (Date) jSpinner1.getValue();
            Instant instant = Instant.ofEpochMilli(fecha.getTime());
            LocalDate localDate = LocalDateTime.ofInstant(instant, ZoneId.systemDefault()).toLocalDate();
            DateTimeFormatter formatoCorto = DateTimeFormatter.ofPattern("dd/MM/yyyy");
            String string =localDate.format(formatoCorto);
            cliente.getTarjeta().setFechaCad(LocalDate.parse(string, formatoCorto));
            ClaseUtil.guardarDatos();
            JOptionPane.showMessageDialog(this, "Cambio realizado", "Cambio Exitoso", JOptionPane.INFORMATION_MESSAGE);
            
            this.dispose();
        }
        catch (HeadlessException | NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Excepción al guardar cambios, compruebe los datos", "Mensaje", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        dispose(); 
    }//GEN-LAST:event_jButton4ActionPerformed

  


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel calleLabel;
    private javax.swing.JTextField calleText;
    private javax.swing.JLabel cifLabel;
    private javax.swing.JTextField cifText;
    private javax.swing.JLabel cityLabel;
    private javax.swing.JTextField cityText;
    private javax.swing.JLabel correoLabel;
    private javax.swing.JTextField correoText;
    private javax.swing.JLabel cpLabel;
    private javax.swing.JFormattedTextField cpText;
    private javax.swing.JLabel dniLabel;
    private javax.swing.JTextField dniText;
    private javax.swing.JLabel fechaCadLabel;
    private javax.swing.JTextField fechaCadText;
    private javax.swing.JLabel formularioLabel;
    private javax.swing.ButtonGroup grupoCliente;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JLabel labelLogo;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameText;
    private javax.swing.JLabel numTarLabel;
    private javax.swing.JFormattedTextField numTarText;
    private javax.swing.JLabel numberLabel;
    private javax.swing.JFormattedTextField numberText;
    private javax.swing.JLabel passLabel;
    private javax.swing.JPasswordField passText;
    private javax.swing.JLabel teleLabel;
    private javax.swing.JFormattedTextField teleText;
    private javax.swing.JLabel tipoUsuLabel;
    private javax.swing.JTextField tipoUsuText;
    private javax.swing.JLabel titularLabel;
    private javax.swing.JTextField titularText;
    private javax.swing.JLabel webLabel;
    private javax.swing.JTextField webText;
    // End of variables declaration//GEN-END:variables
}
