/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package poo.javaeat.interfaz;

import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.Map;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import poo.javaeat.Catering;
import poo.javaeat.ClaseUtil;
import poo.javaeat.Cliente;
import poo.javaeat.Comida;
import poo.javaeat.Empresa;
import poo.javaeat.Particular;
import poo.javaeat.Restaurante;
import poo.javaeat.interfaz.VentanaCliente;
import java.util.Iterator;
import java.util.ArrayList;
import poo.javaeat.Pedido;
import poo.javaeat.Servicio;
/**
 *
 * @author gonza
 */
public class VerPedido extends javax.swing.JDialog {
    
    //Atributos
    private String nombreImagen, rutaImagen, extension = "jpg";
    private File file;
    private BufferedImage bimage;
    private DefaultTableModel dtm2 = new DefaultTableModel();
    private Pedido ped;
    
    /**
     * Creates new form AltaComida
     */
    
    public VerPedido(java.awt.Dialog parent, boolean modal, Pedido ped) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        this.setLocationRelativeTo(null);
        this.ped=ped;
        if (ped.getCatering()!=null){
            ArrayList <Servicio>serv =ped.getCatering().getServiciosSeleccionados();
            for (Servicio s:serv){
                switch (s.getNombre()){
                    case "Camareros": camarerosCB.setSelected(true);
                    case "Cocineros": cocinerosCB.setSelected(true);
                    case "Decoracion": decoracionCB.setSelected(true);
                }
            }
            if (ped.getCatering().isEspacioPrivado()){
                espacioCB.setSelected(true);
            }
        }
        
        precioText.setText(Double.toString(ped.getPrecio())); 
        String columnas2[] = {"NOMBRE", "CANTIDAD"};
        dtm2.setColumnIdentifiers(columnas2);
        tabla.setModel(dtm2);
        System.out.println(ped.getCantComidas());
        rellenaTabla2();
        this.setVisible(true);
    }
    
    /**
     * rellena la tabal de comidas seleccionadas
     * */
    public void rellenaTabla2() { 
        limpiaTabla2();
        for (Map.Entry<String, Integer> c : ped.getCantComidas().entrySet()) {
            dtm2.addRow(new Object [] {c.getKey(),c.getValue()});
        }
        if (!(ped.getCatering()==null)) {
            for (Map.Entry<String, Integer> c : ped.getCatering().getCantComidas().entrySet()) {
            dtm2.addRow(new Object [] {c.getKey(),c.getValue()});
            }   
        }
        
    }
    
    private void getImagen() {
        try {
            labelLogo.setSize(132,120);
            ImageIcon imagen = new ImageIcon("imagenes/JavaEatLogo.png");
            //Se redimensiona
            ImageIcon imgRedimensionada = new ImageIcon(imagen.getImage().getScaledInstance(labelLogo.getWidth(), labelLogo.getHeight(), 1));
            labelLogo.setIcon(imgRedimensionada);
        } catch (Exception e) {
            System.out.println("Error: " + e.toString());
        }
    }

    public void limpiaTabla2() {
        int filas = dtm2.getRowCount();
        for (int i = 0; i < filas; i++) {
            dtm2.removeRow(0);
        }   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        labelLogo = new javax.swing.JLabel();
        precioLabel = new javax.swing.JLabel();
        precioText = new javax.swing.JTextField();
        volverButton = new javax.swing.JButton();
        precioLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        comidasSeleccionadasLabel = new javax.swing.JLabel();
        camarerosCB = new javax.swing.JCheckBox();
        cocinerosCB = new javax.swing.JCheckBox();
        decoracionCB = new javax.swing.JCheckBox();
        espacioCB = new javax.swing.JCheckBox();
        resButton = new javax.swing.JButton();
        clButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 102));

        jLabel1.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CONSULTA PEDIDO");

        getImagen();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(125, 125, 125))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelLogo, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                .addContainerGap())
        );

        precioLabel.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        precioLabel.setText("PRECIO:");

        precioText.setEditable(false);
        precioText.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        precioText.setText("0.0");

        volverButton.setText("Volver");
        volverButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverButtonActionPerformed(evt);
            }
        });

        precioLabel1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        precioLabel1.setText("SERVICIOS:");

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nombre", "Cantidad"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabla);

        comidasSeleccionadasLabel.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        comidasSeleccionadasLabel.setText("Comidas seleccionadas:");

        camarerosCB.setText("Camareros (800€)");
        camarerosCB.setEnabled(false);
        camarerosCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                camarerosCBActionPerformed(evt);
            }
        });

        cocinerosCB.setText("Cocineros (1000€)");
        cocinerosCB.setEnabled(false);
        cocinerosCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cocinerosCBActionPerformed(evt);
            }
        });

        decoracionCB.setText("Decoración (500€)");
        decoracionCB.setEnabled(false);
        decoracionCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decoracionCBActionPerformed(evt);
            }
        });

        espacioCB.setText("Espacio Pricado (1000€)");
        espacioCB.setEnabled(false);
        espacioCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                espacioCBActionPerformed(evt);
            }
        });

        resButton.setBackground(new java.awt.Color(255, 255, 153));
        resButton.setText("VER RESTAURANTE");
        resButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resButtonActionPerformed(evt);
            }
        });

        clButton.setBackground(new java.awt.Color(255, 255, 153));
        clButton.setText("VER CLIENTE");
        clButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clButtonActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 255, 102));
        jButton1.setText("VOLVER");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(comidasSeleccionadasLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(36, 36, 36)
                                        .addComponent(precioLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(67, 67, 67)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(precioLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(precioText, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(19, 19, 19)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(decoracionCB)
                                                    .addComponent(cocinerosCB)
                                                    .addComponent(camarerosCB)
                                                    .addComponent(espacioCB)))))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(clButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(resButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE))
                                .addGap(236, 236, 236)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(volverButton)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(volverButton)
                .addGap(34, 34, 34)
                .addComponent(comidasSeleccionadasLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(precioLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(camarerosCB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cocinerosCB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(decoracionCB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(espacioCB))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(43, 43, 43)
                        .addComponent(resButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(precioLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(precioText, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void volverButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverButtonActionPerformed
        dispose();
    }//GEN-LAST:event_volverButtonActionPerformed

    private void cocinerosCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cocinerosCBActionPerformed

    }//GEN-LAST:event_cocinerosCBActionPerformed

    private void camarerosCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_camarerosCBActionPerformed

    }//GEN-LAST:event_camarerosCBActionPerformed

    private void decoracionCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decoracionCBActionPerformed
        
    }//GEN-LAST:event_decoracionCBActionPerformed

    private void espacioCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_espacioCBActionPerformed
        
    }//GEN-LAST:event_espacioCBActionPerformed

    /**Ve el cliente que ha realizado el pedido
     * 
     * @param evt 
     */
    private void clButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clButtonActionPerformed
        // TODO add your handling code here:
        Cliente c =ped.getCliente();
        if (c.getClass().getSimpleName().equals("Empresa")){
            Empresa e=(Empresa) c;
            vcVerUsu v =new vcVerUsu (this,true,e);
        }
        else{
            Particular p=(Particular) c;
            vcVerUsu v =new vcVerUsu (this,true,p);
        }
    }//GEN-LAST:event_clButtonActionPerformed

    /**VE el restaurante que ha modificado el pedido
     * 
     * @param evt 
     */
    private void resButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resButtonActionPerformed
        // TODO add your handling code here:
        ModRestaurante m =new ModRestaurante (this, true,ped.getRestaurante());
    }//GEN-LAST:event_resButtonActionPerformed

    /**Boton de cerrar
     * 
     * @param evt 
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox camarerosCB;
    private javax.swing.JButton clButton;
    private javax.swing.JCheckBox cocinerosCB;
    private javax.swing.JLabel comidasSeleccionadasLabel;
    private javax.swing.JCheckBox decoracionCB;
    private javax.swing.JCheckBox espacioCB;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelLogo;
    private javax.swing.JLabel precioLabel;
    private javax.swing.JLabel precioLabel1;
    private javax.swing.JTextField precioText;
    private javax.swing.JButton resButton;
    private javax.swing.JTable tabla;
    private javax.swing.JButton volverButton;
    // End of variables declaration//GEN-END:variables
}
